evernote_token: ''
params:
    note_search_filter: 'intitle:jap'
    one_note: 'Everki'
    deck: 'Evernote'
    note_type: 'Evernote'
    parsing_regex: '^(?P<kanji>[^　]+)　(?P<kana>[^　]+)　(?P<translation>.+)$'
